---
title: "Hospital Data_April29"
author: "Rob Wells, Katy Seiter"
date: "4/29/2021"
output: html_document
---


```{r include=FALSE}
#install.packages("slider")
#install.packages("zoo")
#install.packages("gtools")
# vignette("basic-usage", package="googlesheets")
#install.packages("googledrive")
#install.packages("googlesheets4")
#install.packages("kableExtra")
#install.packages("formattable")
library(tidyverse)
library(janitor)
library(lubridate)
library(tidyr)
library(jsonlite)
library(gtools)
library(zoo)  
library(reshape2)
library(slider)
library(formattable)
library(dplyr)
library(purrr)
library(googlesheets4)
library(googledrive)
```

#.
#.
# Hospital Data
#.
#.
# IMPORT THE DAILY TWEET HOSPITAL DATA FROM THE GOOGLE Form

#For Googlesheet access
```{r include=FALSE}
url2 <- ("https://docs.google.com/spreadsheets/d/1ikblX8tikM59ma1AftkqgGbyeZkXB6DuBtwMsVeoGYw/edit?usp=sharing")

hospital <- read_sheet(url2, sheet = "Hospital-TWEET SLIDE",  col_types = NULL, na = "",trim_ws = TRUE)
```


#for download
```{r}
#hospital <- rio::import("/Users/rswells/Dropbox/Classes/Data Fall 2020/ArkansasCovid/Hospital Data - Manual Input - Hospital-TWEET SLIDE.csv", which = "Hospital-TWEET SLIDE")
```

#clean names
```{r include=FALSE}
hospital <- janitor::clean_names(hospital)
hospital$date <- as.Date(hospital$date)
```

```{r}
hospital <- hospital %>% 
  arrange(desc(date))
```  

```{r warning=FALSE}
hospital <- hospital [ -c(1) ]
colnames(hospital)[2:5] <- c("Hospitalized", "Vent", "Ever_Hospitalized", "Ever_on_a_Vent")
hospital[2:5] <- lapply((hospital)[2:5], as.numeric)
glimpse(hospital)
#if restart and need to reimport
#master2 <- rio::import("master_file.csv")
#master2$mydate <- as.Date(master2$mydate)
```


```{r}
main_hospital <- master2 %>% 
  filter(county_nam=="Arkansas_all_counties") %>% 
  select(mydate, confirmed_active, active_cases) 
 
main_hospital2 <- left_join(hospital, main_hospital, by=c("date"="mydate"))
glimpse(main_hospital2)
```

#Hospital Math

```{r}
hospital1 <- main_hospital2 %>% 
  mutate(New_Admits = (Ever_Hospitalized-lead(Ever_Hospitalized))) %>% 
  mutate(Hosp_Change_from_Yesterday = (Hospitalized-lead(Hospitalized))) %>% 
  mutate(New_Discharges_Deaths = (New_Admits-Hosp_Change_from_Yesterday)) %>% 
  mutate(Pct_Vent = (Vent/Hospitalized)*100) %>% 
  mutate(New_on_Vent = (Ever_on_a_Vent-lead(Ever_on_a_Vent,na.rm=TRUE)))%>% 
  mutate(Pct_Hospitalized = (Hospitalized/active_cases)*100)

# hospital1 <- hospital1 %>%
#   filter(date ==(today))

# hospital1 <- hospital1 %>%
#   filter(date >=("2020-11-19"))

 hospital1 <- hospital1 %>% 
   filter(date >(yesterday))
#Cut rows from df
#hospital1 <- slice(hospital1, -c(8))

hospital1$Pct_Vent <- round(hospital1$Pct_Vent, 2) 
hospital1$Pct_Hospitalized <- round(hospital1$Pct_Hospitalized, 2) 

hospital1
```

```{r}
#Join today's with hospital master.csv
hospital_master <- rio::import("https://raw.githubusercontent.com/Arkansascovid/Main/master/hospital_master.csv")
hospital_master <- hospital_master [ -c(1) ]
hospital_master$date <- lubridate::ymd(hospital_master$date)
hospital_master[2:13] <- lapply((hospital_master)[2:13], as.numeric)

hospital_master$Pct_Vent <- round(hospital_master$Pct_Vent, 2) 
hospital_master$Pct_Hospitalized <- round(hospital_master$Pct_Hospitalized, 2) 

glimpse(hospital_master)
```

```{r}
#make hospital_master.csv

hospital_master <- rbind(hospital1, hospital_master)

 hospital_master <- hospital_master %>% 
   arrange(desc(date)) %>% 
   distinct()

#edit out rows if needed
#hospital_master <- slice(hospital_master, -c(3,4))


head(hospital_master)
write.csv(hospital_master, file = "MasterData/hospital_master.csv")
```

```{r}
#Flourish - May 1, 2020 filter
hospital_FLOURISH <- hospital_master %>%
  filter(date >= "2020-05-01")
#hospital_FLOURISH <- hospital_FLOURISH[ -c(1) ]
write.csv(hospital_FLOURISH, file = "HomePageData/hospital_FLOURISH.csv")
```

#hospital daily tweet slide
```{r}
#cute extra column from hospital_master
#hospital_master <- hospital_master[ -c(1) ]

hospital2 <- hospital_master %>% 
    filter(date>=(yesterday)) %>% 
  select(date, Hospitalized, Vent, New_Admits, New_on_Vent, New_Discharges_Deaths, Ever_Hospitalized, Ever_on_a_Vent)

hospital2 <- hospital2 %>% 
  rename(Date = date, On_Vents = Vent, Ever_on_Vent = Ever_on_a_Vent)

h <- t(hospital2)

h <- data.frame(Value = row.names(h), h)
colnames(h)[1:3] <- c("Value","Today", "Yesterday")
row.names(h) <- NULL


library(kableExtra)
h %>% 
  kable() %>%
  kable_styling("striped")
```


# IMPORT THE DAILY EMAILED HOSPITAL DATA FROM THE GOOGLE Form

```{r include=FALSE}
url3 <- ("https://docs.google.com/spreadsheets/d/1ikblX8tikM59ma1AftkqgGbyeZkXB6DuBtwMsVeoGYw/edit?usp=sharing")

hospitalemail <- read_sheet(url3, sheet = "Hospital_email",  col_types = NULL, na = "",trim_ws = TRUE)
```

```{r}
# hospitalemail <- rio::import("/Users/rswells/Dropbox/Classes/Data Fall 2020/ArkansasCovid/Hospital Data - Manual Input.xlsx", which = "Hospital_email")
```

```{r}
#clean names
hospitalemail <- janitor::clean_names(hospitalemail)
hospitalemail  <- hospitalemail  %>% 
  arrange(desc(date))
hospitalemail  <- hospitalemail  [ -c(1) ]
glimpse(hospitalemail)
colnames(hospitalemail)[1:10] <- c("Date", "Hospitalized", "Total_Beds", "Total_Beds_Available", "Total_ICU_Beds", "Total_ICU_Beds_Available", "Total_Vents", "Total_Vents_Available","Total_Covid_In_ICU","Total_Covid_Patients_Vent")
hospitalemail$Date <- as.Date(hospitalemail$Date)
```


```{r}
write.csv(hospitalemail, file = "MasterData/hospital_email_data.csv")
head(hospitalemail)
```
