---
title: "Hospital"
author: "By Rob Wells. Thanks to Ravi Brock"
date: "6/01/2021"
output: pdf_document
---

# Hospital Data from ADH

- **Retrieves data from the Arkansas Dept of Health.**

#Line 250 Remember to Enter Today's Date in the slide: "ADH Data for June 1, 2021",

# Part 1: Import State Data, Clean It

```{r include=FALSE}
#install.packages("tidyverse",dependencies = TRUE)
#install.packages("slider")
#install.packages("zoo")
#install.packages("gtools")
#install.packages("kableExtra")
#install.packages("formattable")
#install.packages("janitor")
#install.packages("reshape2")
library(tidyverse)
library(janitor)
library(lubridate)
library(jsonlite)
library(gtools)
library(zoo)  
library(reshape2)
library(slider)
library(formattable)


```

## Retrieve Regional Hospital Data from ADH FEED
```{r}
#New County json feed
#38 Variables
q <- fromJSON('https://services.arcgis.com/PwY9ZuZRDiI5nXUB/ArcGIS/rest/services/UPDATED_ADH_COVID19_HEALTH_REGION_METRICS/FeatureServer/0/query?where=0%3D0&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&resultType=none&distance=0.0&units=esriSRUnit_Meter&returnGeodetic=false&outFields=*&returnGeometry=true&returnCentroid=false&featureEncoding=esriDefault&multipatchOption=xyFootprint&maxAllowableOffset=&geometryPrecision=&outSR=&datumTransformation=&applyVCSProjection=false&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnExtentOnly=false&returnQueryGeometry=false&returnDistinctValues=false&cacheHint=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&having=&resultOffset=&resultRecordCount=&returnZ=false&returnM=false&returnExceededLimitFeatures=true&quantizationParameters=&sqlFormat=none&f=pjson&token=')

#OnVents and PositiveAdmits represent the same data in the daily Tweet slide for vents and total hospitalized
hospital_new <- q[["features"]][["attributes"]]

hospital_new$Date <- Sys.Date()


#makes a spreadsheet
#write.csv(hospital, "hospital_ADH_API.csv")

#check math against the hospital tweet slide
sum(hospital_new$PositiveAdmits)
sum(hospital_new$OnVents)

```
#Set Dates
```{r}
#today's date
today <- Sys.Date()

#NOTE: IF YOU ARE RUNNING THIS A DAY LATE, USE THIS CODE TO WORK PROPERLY
#today <- Sys.Date()-1
#today_county$mydate <-"2020-09-22- THE OLD DATE...."

#yesterday's date
yesterday <- (today-1)

```

#Quick Calculation of State Totals 
```{r}
#Calculate statewide totals

hospital_new <- hospital_new %>%
  janitor::adorn_totals("row")

hospital_new <- as.data.frame(hospital_new)
```

```{r}
glimpse(hospital_new)
```

```{r}
hospital_today <- hospital_new %>% 
  filter(OBJECTID =="Total") 

hospital_today$date <- today

hospital_today <- hospital_today %>% 
  rename('Hospitalized'= PositiveAdmits, 'Vent'= OnVents)

hospital_today <- hospital_today %>% 
  select(date, Hospitalized, Vent)

#One time fix
# hospital_today$Hospitalized <- ("187")
# hospital_today$Vent <- ("33")

# hospital_today [2:3] <- lapply(hospital_today [2:3], as.numeric)
# glimpse(hospital_today)

```


```{r}
hospital_master <- rio::import("https://raw.githubusercontent.com/Arkansascovid/Main/master/MasterData/hospital_master.csv")

hospital_master <- hospital_master %>% 
  select(date, Hospitalized, Vent, Hosp_Change_from_Yesterday, Pct_Vent, Pct_Hospitalized, active_cases, confirmed_active)

#roll back a date
# hospital_master <- hospital_master %>%
#     filter(date<=("2021-05-30"))


#Join new to old
hospital_master <- smartbind(hospital_today, hospital_master)
hospital_master$date <- as.Date(hospital_master$date)
glimpse(hospital_master)
```


```{r}
main_hospital <- master2 %>% 
  filter(county_nam=="Arkansas_all_counties") %>% 
  select(mydate, confirmed_active, active_cases) %>% 
  rename('date' = mydate)
 
# #If needed Roll back a day
#  main_hospital <- main_hospital %>%
#     filter(date<=("2021-05-31"))
 
 

hospital2 <- hospital_master %>% 
  select(date, Hospitalized, Vent)

main_hospital2 <- inner_join(main_hospital, hospital2, by=c("date"="date"))
 
# main_hospital3 <- main_hospital2 %>% 
#   mutate(Vent_Change_from_Yesterday = (Vent-lead(Vent)))


# main_hospital2 <- inner_join(main_hospital, hospital_master, by=c("date"="date", "active_cases"="active_cases", "confirmed_active"="confirmed_active"))


# glimpse(main_hospital)
# glimpse(hospital_master)
glimpse(main_hospital2)
```


#Hospital Math

```{r}
hospital1 <- main_hospital2 %>% 
  mutate(Hosp_Change_from_Yesterday = (Hospitalized-lead(Hospitalized))) %>% 
  #mutate(Vent_Change_from_Yesterday = (Vent-lead(Vent))) %>% 
  mutate(Pct_Vent = (Vent/Hospitalized)*100) %>% 
  mutate(Pct_Hospitalized = (Hospitalized/active_cases)*100)

# hospital1 <- hospital1 %>%
#   filter(date ==(today))

# hospital1 <- hospital1 %>%
#   filter(date >=("2021-05-17"))



hospital1 <- hospital1 %>% 
   filter(date >(yesterday))
#Cut rows from df
#hospital1 <- slice(hospital1, -c(1))

hospital1$Pct_Vent <- round(hospital1$Pct_Vent, 2) 
hospital1$Pct_Hospitalized <- round(hospital1$Pct_Hospitalized, 2) 

hospital1
```

```{r}
#make hospital_master.csv

hospital_master <- hospital_master %>% 
  filter(date <= yesterday)

hospital_master <- rbind(hospital1, hospital_master)

 hospital_master <- hospital_master %>% 
   arrange(desc(date)) %>% 
   distinct()

#edit out rows if needed
#hospital_master <- slice(hospital_master, -c(2))


head(hospital_master)
glimpse(hospital_master)
write.csv(hospital_master, file = "MasterData/hospital_master.csv")
```


```{r}
#Flourish - May 1, 2020 filter
hospital_FLOURISH <- hospital_master %>%
  filter(date >= "2020-05-01")
#hospital_FLOURISH <- hospital_FLOURISH[ -c(1) ]
write.csv(hospital_FLOURISH, file = "HomePageData/hospital_FLOURISH.csv")
```

#Hospital daily tweet slide
#June 7 version with change and date automatically pasted in.
```{r}
#cut extra column from hospital_master
#hospital_master <- hospital_master[ -c(1) ]

hospital2 <- hospital_master %>% 
    filter(date>=(yesterday)) %>% 
  select(date, Hospitalized, Vent, Hosp_Change_from_Yesterday)

hospital2 <- hospital2 %>% 
  rename(Date = date, On_Vents = Vent, Hospital_Change_from_Yesterday = Hosp_Change_from_Yesterday)

#Create single value for daily change
change <- hospital2 %>% 
  filter(Date == (today)) 

change1 <- change$Hospital_Change_from_Yesterday


#p + xlab(paste0("Today's change in hospitalizations: ", change1[1]))
#https://stackoverflow.com/questions/29359111/adding-output-of-print-function-to-ggplot-chart-r

hh <- t(hospital2)

hh <- data.frame(Value = row.names(hh), hh)
colnames(hh)[1:3] <- c("Value","Today", "Yesterday")
row.names(hh) <- NULL

df5 <- melt(hospital2[,c("Date", "Hospitalized", "On_Vents")], id.vars = 1)

df5 <- df5 %>% 
   rename(Detail = variable, Amount = value)

ggplot(df5,aes(x = Date, y = Amount, label = Amount, fill= Detail)) + 
geom_bar(stat="identity", position="dodge", color="white")+
scale_fill_manual(values=c("#B3BF08", "#08B3BF", "#D68037"))+
scale_y_continuous(limits=c(0, 350))  +
  theme_bw() + 
  theme(
    plot.title = element_text(face = "bold", size = 16),
    legend.background = element_rect(fill = "white", size = .01, colour = "white"),
    legend.justification = c(0, 1),
    #adjust the box position. First number horizontal, second, vertical 
    legend.position = c(.617, .96),
    #legend.position = c(.617, .38),
    #legend.position = c(.1, .38),
    axis.ticks = element_line(colour = "grey70", size = 0.2),
    panel.grid.major = element_line(colour = "grey70", size = 0.2),
    panel.grid.minor = element_blank()
  )+
   geom_col(position = position_dodge2(width = 0.9, preserve = "single")) +
  geom_text(position = position_dodge2(width = 0.9, preserve = "single"), vjust=-0.5, hjust=+0.5) +
  labs(title = "COVID-19 Hospitalizations in Arkansas Announced Today", 
       subtitle = (paste0("Today's change in hospitalizations: ", change1[1])),
       caption = (paste0("Graphic by Arkansascovid.com. ADH Data for ", today[1])),
       y="Amount",
       x="Date")
ggsave("Hospital.png",device = "png",width=9,height=6, dpi=400)
```

-**30**