---
title: "Nursing Home Reports"
author: "Rob Wells"
date: "10/29/2020"
output: pdf_document
---

```{r include=FALSE}
#install.packages("slider")
#install.packages("zoo")
#install.packages("gtools")
# vignette("basic-usage", package="googlesheets")
#install.packages("googledrive")
#install.packages("googlesheets4")
#install.packages("ggthemes")
library(tidyverse)
library(janitor)
library(lubridate)
library(googlesheets4)
library(googledrive)
library(tidyr)
library(jsonlite)
library(gtools)
library(zoo)  
library(reshape2)
library(slider)
library(twitteR)
library(rtweet)
library(stringr)
library(tidytext)
library(ggthemes) 
library(purrr)
library(rio)

```

#Nursing home reports summary
#https://docs.google.com/spreadsheets/d/1s05eM7yTRbs1zkIajQ7qyycOqJ8Fk1qPwQlkzp-JKUY/edit?usp=sharing
```{r}
url <- ("https://docs.google.com/spreadsheets/d/1s05eM7yTRbs1zkIajQ7qyycOqJ8Fk1qPwQlkzp-JKUY/edit?usp=sharing")

nursing <- read_sheet(url, sheet="Master_Sheet")
nursing <- as.data.frame(nursing)
nursing <- janitor::clean_names(nursing)
nursing$date <- ymd(nursing$date_of_survey)
glimpse(nursing)
```

#Number complaint vs Not
```{r}
Compliant <- nursing %>% count(compliant_or_not) %>% 
  group_by(compliant_or_not) %>% 
  arrange(desc(n))
Compliant
```

#------------------------------------------------------------------------------#
#                      Tokenize and Summarize                                  #
#------------------------------------------------------------------------------#
#from book: https://www.tidytextmining.com/tidytext.html #
#from tutorial: http://varianceexplained.org/r/trump-tweets/
```{r}
#Define characters
reg <- "([^A-Za-z\\d#@']|'(?![A-Za-z\\d#@]))"
#
```
#
```{r}
nursing2 <- nursing %>%
  filter(!str_detect(category, '^"')) %>%
  mutate(category = str_replace_all(category, "https://t.co/[A-Za-z\\d]+|&amp;", "")) %>%
  unnest_tokens(word, category, token = "regex", pattern = reg) %>%
  filter(!word %in% stop_words$word,
         str_detect(word, "[a-z]"))
```

#Major Issues
```{r}
Issues <- nursing2 %>% count(word) %>% 
  group_by(word) %>% 
  arrange(desc(n))

Issues
```

